### ISSUE TITLE
Crashing Error

### ISSUE THREAD

**Issue by DanKeith** [VoltaicHQ/Progress-Sheet-Updater#16]
![image](https://user-images.githubusercontent.com/82262268/114264739-3e034f00-9a1f-11eb-98d0-092090f8648a.png)

I'm having this error a few seconds after launching the program.

**Comment by Y0ndaime** [comment]
One of your score files contains a NUL Byte which csv can't seem to handle (this often happens if your pc crashes while kovaaks is open). You can try manually deleting them by looking if you see an empty file in your stats, or by moving a few stats out and then trying again, repeating that until it works, then checking which stat is causing the error. Or you can use this https://github.com/Y0ndaime/KovaaksStatRemover/releases/tag/1.2 (I was only able to test this once, so I'd appreciate feedback, if you decide to use my tool).

**Comment by DanKeith** [comment]
Thanks! The Progress Sheet Updater was working again when I found and deleted two empty csv files in my stats folder. 

But at first, I tried using the stat remover, but it's giving me this error:
![Screenshot_2](https://user-images.githubusercontent.com/82262268/114288323-4f8d3b00-9aa1-11eb-8cdf-54198cea444c.png)
