### ISSUE TITLE
Sheets API error: The caller does not have permission

### ISSUE THREAD

**Issue by RoastyToastyBoi** [VoltaicHQ/Progress-Sheet-Updater#40]
![image](https://github.com/VoltaicHQ/Progress-Sheet-Updater/assets/154607266/b2746120-5711-433f-b300-fa847fa55f6e)

**Comment by vuhnger** [comment]
Any updates on this?

**Comment by Y0ndaime** [comment]
The google account that is making the request to the sheets API does not have permission to access the document. Make sure you linked a document that the google account, which you authenticated in the program, can access. Sometimes a different account is used since it is already logged in in the browser. You can delete token.pickle to redo the auth flow
